using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Resources;
[assembly: AssemblyTitle("Jkop.UWP")]
[assembly: AssemblyProduct("Jkop.UWP")]
[assembly: AssemblyDescription("Jkop.UWP")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyCopyright("Copyright")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("11A07900-2D5B-B735-81CE-593EEDF1E17D")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
